/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

//import DSModel.main;
import java.awt.CardLayout;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.BorderFactory.createLineBorder;
import javax.swing.JLabel;
import javax.xml.ws.ServiceMode;
import model.NguoiDung;
import model.ServiceModel;

/**
 *
 * @author nguye
 */
public class Main3 extends javax.swing.JFrame {

    private CardLayout MENUCard;
    private static final int ACCOUNT = 0;
    private static final int MANAGER = 1;
    private static final int SETTING = 2;
    private static final int SEARCH = 3;
    private static final int STATISTICAL = 4;
    private static final int REPORT = 5;
    private static final int ASSIGNMENT = 6;
    private static final int INFOMATION = 7;
    private static final int THICKNESS = 2;
    private static final String ACCOUNTMENU = "thẻ tài khoản";
    private static final String MANAGERMENU = "Quản lí";
    private static final String MENUMAIN = "menu card";
    private static final String Search="Tìm kiếm";
private static final String TEST = "test";
    public String maNguoiDung = "";
    public String matKhau = "";
    /**
     * Creates new form Main3
     */
    private String quyenQuanLy;
    private NguoiDung nguoiDung;

    public Main3(NguoiDung nguoiDung, String quyen) {
        this.quyenQuanLy = quyen;
        this.nguoiDung = nguoiDung;
        initComponents();
        setLocationRelativeTo(null);
        setOptionMenu();
        MENUCard = (CardLayout) CardMenu.getLayout();
//        nguoiDung.showInfo();
    }
    
    public Main3(String maNguoiDung, int loaiNguoiDung){
        initComponents();
        setLocationRelativeTo(null);
        setOptionMenu();
        MENUCard = (CardLayout) CardMenu.getLayout();
        
        getUserInfo(maNguoiDung);
    }
    
    private void getUserInfo(String maNguoiDung) {
        if (maNguoiDung == "admin") {
            tenNguoiDungTF.setText("Admin");
            quyenTF.setText("Quản lý");
            quanLyMENU.setVisible(true);
        } else {
            try {
                String blankQuery = "call timGiangVien('%s', '', '', '', '')";
                String sqlQuery = String.format(blankQuery, maNguoiDung);
                ResultSet rs = ServiceModel.getResultSetFromSQLQuery(sqlQuery, "tim giang vien");
                String ten = "";
                while (rs.next()) {
                    ten = (String) rs.getObject(2);
                }
                tenNguoiDungTF.setText(ten);
                quyenTF.setText("Giảng viên");
                quanLyMENU.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(Main3.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootPN = new javax.swing.JPanel();
        minisizeLB = new javax.swing.JLabel();
        closeLB = new javax.swing.JLabel();
        backLB = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tenNguoiDungTF = new javax.swing.JLabel();
        quyenTF = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        CardMenu = new javax.swing.JPanel();
        theChucNangChinh = new javax.swing.JPanel();
        taiKhoanMENU = new javax.swing.JLabel();
        quanLyMENU = new javax.swing.JLabel();
        caiDatMENU = new javax.swing.JLabel();
        baoCaoMENU = new javax.swing.JLabel();
        timKiemMENU = new javax.swing.JLabel();
        thongKeMENU = new javax.swing.JLabel();
        phanCongMENU = new javax.swing.JLabel();
        thongTinMENU = new javax.swing.JLabel();
        thongTinMENU2 = new javax.swing.JLabel();
        theTaiKhoan = new javax.swing.JPanel();
        dangXuatMENUITEM = new javax.swing.JLabel();
        doiMatKhauMENUITEM = new javax.swing.JLabel();
        thongTinTaiKhoanMENUITEM = new javax.swing.JLabel();
        test = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Timkiem = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        timKiemSinhVienBtn = new javax.swing.JButton();
        theQuanLy2 = new javax.swing.JPanel();
        quanLyGiangVien2 = new javax.swing.JButton();
        quanLyLoaiHinh2 = new javax.swing.JButton();
        quanLyHocPhan6 = new javax.swing.JButton();
        quanLyHocPhan7 = new javax.swing.JButton();
        quanLyHocPhan8 = new javax.swing.JButton();
        quanLySinhVien2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        thongTinMENU1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        rootPN.setBackground(color.Color.WHITE);

        minisizeLB.setBackground(new java.awt.Color(255, 51, 51));
        minisizeLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minisizeLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Subtract_24px.png"))); // NOI18N
        minisizeLB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        minisizeLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minisizeLBMouseClicked(evt);
            }
        });

        closeLB.setBackground(new java.awt.Color(255, 51, 51));
        closeLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Delete_24px.png"))); // NOI18N
        closeLB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        closeLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeLBMouseClicked(evt);
            }
        });

        backLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Undo_24px.png"))); // NOI18N
        backLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLBMouseClicked(evt);
            }
        });

        jPanel2.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Phần mềm quản lý khối lượng");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setOpaque(true);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Xin chào,");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Bạn đang là");

        tenNguoiDungTF.setText("Tên người dùng");

        quyenTF.setText("Quyền");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tenNguoiDungTF, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(quyenTF, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(61, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(tenNguoiDungTF)
                    .addComponent(quyenTF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(713, 700));

        CardMenu.setOpaque(false);
        CardMenu.setLayout(new java.awt.CardLayout());

        theChucNangChinh.setBackground(new java.awt.Color(153, 255, 51));
        theChucNangChinh.setOpaque(false);

        taiKhoanMENU.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        taiKhoanMENU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        taiKhoanMENU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Account_72px.png"))); // NOI18N
        taiKhoanMENU.setText("Tài khoản");
        taiKhoanMENU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        taiKhoanMENU.setIconTextGap(15);
        taiKhoanMENU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        taiKhoanMENU.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                taiKhoanMENUMouseMoved(evt);
            }
        });
        taiKhoanMENU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taiKhoanMENUMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                taiKhoanMENUMouseExited(evt);
            }
        });

        quanLyMENU.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        quanLyMENU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quanLyMENU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Tasks_72px.png"))); // NOI18N
        quanLyMENU.setText("Quản lý");
        quanLyMENU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        quanLyMENU.setIconTextGap(15);
        quanLyMENU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        quanLyMENU.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                quanLyMENUMouseMoved(evt);
            }
        });
        quanLyMENU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quanLyMENUMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                quanLyMENUMouseExited(evt);
            }
        });

        caiDatMENU.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        caiDatMENU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        caiDatMENU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Settings_72px.png"))); // NOI18N
        caiDatMENU.setText("Cài đặt");
        caiDatMENU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        caiDatMENU.setIconTextGap(15);
        caiDatMENU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        caiDatMENU.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                caiDatMENUMouseMoved(evt);
            }
        });
        caiDatMENU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caiDatMENUMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                caiDatMENUMouseExited(evt);
            }
        });

        baoCaoMENU.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        baoCaoMENU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        baoCaoMENU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Edit_Graph_Report_72px.png"))); // NOI18N
        baoCaoMENU.setText("Báo cáo");
        baoCaoMENU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        baoCaoMENU.setIconTextGap(15);
        baoCaoMENU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        baoCaoMENU.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                baoCaoMENUMouseMoved(evt);
            }
        });
        baoCaoMENU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                baoCaoMENUMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                baoCaoMENUMouseExited(evt);
            }
        });

        timKiemMENU.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        timKiemMENU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timKiemMENU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Search_72px.png"))); // NOI18N
        timKiemMENU.setText("Tìm kiếm");
        timKiemMENU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        timKiemMENU.setIconTextGap(15);
        timKiemMENU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        timKiemMENU.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                timKiemMENUMouseMoved(evt);
            }
        });
        timKiemMENU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timKiemMENUMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                timKiemMENUMouseExited(evt);
            }
        });

        thongKeMENU.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        thongKeMENU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thongKeMENU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Statistics_72px_1.png"))); // NOI18N
        thongKeMENU.setText("Thống kê");
        thongKeMENU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        thongKeMENU.setIconTextGap(15);
        thongKeMENU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        thongKeMENU.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                thongKeMENUMouseMoved(evt);
            }
        });
        thongKeMENU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thongKeMENUMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                thongKeMENUMouseExited(evt);
            }
        });

        phanCongMENU.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        phanCongMENU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        phanCongMENU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Flow_Chart_72px.png"))); // NOI18N
        phanCongMENU.setText("Kê khai");
        phanCongMENU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        phanCongMENU.setIconTextGap(15);
        phanCongMENU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        phanCongMENU.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                phanCongMENUMouseMoved(evt);
            }
        });
        phanCongMENU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phanCongMENUMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                phanCongMENUMouseExited(evt);
            }
        });

        thongTinMENU.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        thongTinMENU.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thongTinMENU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Info_72px_1.png"))); // NOI18N
        thongTinMENU.setText("Thông tin");
        thongTinMENU.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        thongTinMENU.setIconTextGap(15);
        thongTinMENU.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        thongTinMENU.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                thongTinMENUMouseMoved(evt);
            }
        });
        thongTinMENU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                thongTinMENUMouseExited(evt);
            }
        });

        thongTinMENU2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        thongTinMENU2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thongTinMENU2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/checkbox-resize.png"))); // NOI18N
        thongTinMENU2.setText("Đồ án");
        thongTinMENU2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        thongTinMENU2.setIconTextGap(15);
        thongTinMENU2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        thongTinMENU2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                thongTinMENU2MouseMoved(evt);
            }
        });
        thongTinMENU2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                thongTinMENU2MouseExited(evt);
            }
        });

        javax.swing.GroupLayout theChucNangChinhLayout = new javax.swing.GroupLayout(theChucNangChinh);
        theChucNangChinh.setLayout(theChucNangChinhLayout);
        theChucNangChinhLayout.setHorizontalGroup(
            theChucNangChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(theChucNangChinhLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(theChucNangChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(theChucNangChinhLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(theChucNangChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(theChucNangChinhLayout.createSequentialGroup()
                                .addComponent(phanCongMENU, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(thongTinMENU, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(theChucNangChinhLayout.createSequentialGroup()
                                .addComponent(baoCaoMENU, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(thongKeMENU, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(theChucNangChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thongTinMENU2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(quanLyMENU, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(196, Short.MAX_VALUE))
                    .addGroup(theChucNangChinhLayout.createSequentialGroup()
                        .addComponent(taiKhoanMENU, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(timKiemMENU, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(caiDatMENU, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        theChucNangChinhLayout.setVerticalGroup(
            theChucNangChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(theChucNangChinhLayout.createSequentialGroup()
                .addGroup(theChucNangChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(taiKhoanMENU, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caiDatMENU, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timKiemMENU, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(theChucNangChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(theChucNangChinhLayout.createSequentialGroup()
                        .addGroup(theChucNangChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(thongKeMENU, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(baoCaoMENU, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, theChucNangChinhLayout.createSequentialGroup()
                        .addComponent(thongTinMENU2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(theChucNangChinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quanLyMENU, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thongTinMENU, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phanCongMENU, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(629, Short.MAX_VALUE))
        );

        CardMenu.add(theChucNangChinh, "menu card");

        theTaiKhoan.setOpaque(false);

        dangXuatMENUITEM.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        dangXuatMENUITEM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dangXuatMENUITEM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Logout_Rounded_Up_72px.png"))); // NOI18N
        dangXuatMENUITEM.setText("Đăng xuất");
        dangXuatMENUITEM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dangXuatMENUITEM.setIconTextGap(15);
        dangXuatMENUITEM.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        dangXuatMENUITEM.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                dangXuatMENUITEMMouseMoved(evt);
            }
        });
        dangXuatMENUITEM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dangXuatMENUITEMMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dangXuatMENUITEMMouseExited(evt);
            }
        });

        doiMatKhauMENUITEM.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        doiMatKhauMENUITEM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doiMatKhauMENUITEM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Encrypt_72px.png"))); // NOI18N
        doiMatKhauMENUITEM.setText("Đổi mật khẩu");
        doiMatKhauMENUITEM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        doiMatKhauMENUITEM.setIconTextGap(15);
        doiMatKhauMENUITEM.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        doiMatKhauMENUITEM.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                doiMatKhauMENUITEMMouseMoved(evt);
            }
        });
        doiMatKhauMENUITEM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doiMatKhauMENUITEMMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                doiMatKhauMENUITEMMouseExited(evt);
            }
        });

        thongTinTaiKhoanMENUITEM.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        thongTinTaiKhoanMENUITEM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thongTinTaiKhoanMENUITEM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Info_72px_1.png"))); // NOI18N
        thongTinTaiKhoanMENUITEM.setText("Thông tin tài khoản");
        thongTinTaiKhoanMENUITEM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        thongTinTaiKhoanMENUITEM.setIconTextGap(15);
        thongTinTaiKhoanMENUITEM.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        thongTinTaiKhoanMENUITEM.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                thongTinTaiKhoanMENUITEMMouseMoved(evt);
            }
        });
        thongTinTaiKhoanMENUITEM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thongTinTaiKhoanMENUITEMMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                thongTinTaiKhoanMENUITEMMouseExited(evt);
            }
        });

        javax.swing.GroupLayout theTaiKhoanLayout = new javax.swing.GroupLayout(theTaiKhoan);
        theTaiKhoan.setLayout(theTaiKhoanLayout);
        theTaiKhoanLayout.setHorizontalGroup(
            theTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(theTaiKhoanLayout.createSequentialGroup()
                .addGroup(theTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(theTaiKhoanLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(thongTinTaiKhoanMENUITEM, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120)
                        .addComponent(doiMatKhauMENUITEM, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(theTaiKhoanLayout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(dangXuatMENUITEM, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        theTaiKhoanLayout.setVerticalGroup(
            theTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(theTaiKhoanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dangXuatMENUITEM, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(theTaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(thongTinTaiKhoanMENUITEM, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(doiMatKhauMENUITEM, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CardMenu.add(theTaiKhoan, "thẻ tài khoản");

        test.setOpaque(false);

        jLabel2.setText("test ");

        javax.swing.GroupLayout testLayout = new javax.swing.GroupLayout(test);
        test.setLayout(testLayout);
        testLayout.setHorizontalGroup(
            testLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, testLayout.createSequentialGroup()
                .addContainerGap(441, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
        );
        testLayout.setVerticalGroup(
            testLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(testLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(942, Short.MAX_VALUE))
        );

        CardMenu.add(test, "test");

        Timkiem.setOpaque(false);

        jButton2.setText("Tìm kiếm môn học");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Tìm kiếm phân công");

        jButton4.setText("Tìm kiếm giảng viên");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        timKiemSinhVienBtn.setText("Tìm kiếm sinh viên");
        timKiemSinhVienBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timKiemSinhVienBtnMouseClicked(evt);
            }
        });
        timKiemSinhVienBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiemSinhVienBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TimkiemLayout = new javax.swing.GroupLayout(Timkiem);
        Timkiem.setLayout(TimkiemLayout);
        TimkiemLayout.setHorizontalGroup(
            TimkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimkiemLayout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(TimkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timKiemSinhVienBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(381, Short.MAX_VALUE))
        );
        TimkiemLayout.setVerticalGroup(
            TimkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimkiemLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(timKiemSinhVienBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(677, Short.MAX_VALUE))
        );

        CardMenu.add(Timkiem, "Tìm kiếm");

        theQuanLy2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)), "Quản Lí", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 36), new java.awt.Color(102, 102, 102))); // NOI18N
        theQuanLy2.setOpaque(false);
        theQuanLy2.setPreferredSize(new java.awt.Dimension(633, 500));

        quanLyGiangVien2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        quanLyGiangVien2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/teacher.png"))); // NOI18N
        quanLyGiangVien2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyGiangVienActionPerformed(evt);
            }
        });

        quanLyLoaiHinh2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        quanLyLoaiHinh2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/if_26_Alphabet_2064501.png"))); // NOI18N
        quanLyLoaiHinh2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyLoaiHinhActionPerformed(evt);
            }
        });

        quanLyHocPhan6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        quanLyHocPhan6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/blackboard.png"))); // NOI18N
        quanLyHocPhan6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyHocPhanActionPerformed(evt);
            }
        });

        quanLyHocPhan7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        quanLyHocPhan7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/split.png"))); // NOI18N
        quanLyHocPhan7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyHocPhan1ActionPerformed(evt);
            }
        });

        quanLyHocPhan8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        quanLyHocPhan8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/notebook.png"))); // NOI18N
        quanLyHocPhan8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLyHocPhan2ActionPerformed(evt);
            }
        });

        quanLySinhVien2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        quanLySinhVien2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/student (1).png"))); // NOI18N
        quanLySinhVien2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quanLySinhVienActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 153, 255));
        jLabel17.setText("Giảng Viên");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 153, 255));
        jLabel18.setText("Sinh Viên");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 153, 255));
        jLabel19.setText("Loại Hình");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 153, 255));
        jLabel20.setText("Học Phần");

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 153, 255));
        jLabel23.setText("Phân Công Hướng dẫn");

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 153, 255));
        jLabel24.setText("Chi Tiết Phân Công");

        javax.swing.GroupLayout theQuanLy2Layout = new javax.swing.GroupLayout(theQuanLy2);
        theQuanLy2.setLayout(theQuanLy2Layout);
        theQuanLy2Layout.setHorizontalGroup(
            theQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(theQuanLy2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(theQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(theQuanLy2Layout.createSequentialGroup()
                        .addGroup(theQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quanLyGiangVien2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(theQuanLy2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(theQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(quanLySinhVien2, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(theQuanLy2Layout.createSequentialGroup()
                            .addGroup(theQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(quanLyHocPhan6, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(quanLyLoaiHinh2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(theQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(theQuanLy2Layout.createSequentialGroup()
                                    .addGap(28, 28, 28)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, theQuanLy2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(theQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(quanLyHocPhan8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(quanLyHocPhan7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(232, Short.MAX_VALUE))
            .addGroup(theQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(theQuanLy2Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(501, Short.MAX_VALUE)))
        );
        theQuanLy2Layout.setVerticalGroup(
            theQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(theQuanLy2Layout.createSequentialGroup()
                .addGroup(theQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(quanLySinhVien2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quanLyGiangVien2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(theQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(theQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(quanLyLoaiHinh2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quanLyHocPhan8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(theQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(theQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(quanLyHocPhan6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quanLyHocPhan7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addComponent(jLabel23)
                .addContainerGap())
            .addGroup(theQuanLy2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(theQuanLy2Layout.createSequentialGroup()
                    .addGap(431, 431, 431)
                    .addComponent(jLabel24)
                    .addContainerGap(641, Short.MAX_VALUE)))
        );

        CardMenu.add(theQuanLy2, "Quản lí");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CardMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CardMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        thongTinMENU1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        thongTinMENU1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        thongTinMENU1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Info_72px_1.png"))); // NOI18N
        thongTinMENU1.setText("Thông tin");
        thongTinMENU1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        thongTinMENU1.setIconTextGap(15);
        thongTinMENU1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        thongTinMENU1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                thongTinMENU1MouseMoved(evt);
            }
        });
        thongTinMENU1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                thongTinMENU1MouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Delete_24px.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_Subtract_24px.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout rootPNLayout = new javax.swing.GroupLayout(rootPN);
        rootPN.setLayout(rootPNLayout);
        rootPNLayout.setHorizontalGroup(
            rootPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPNLayout.createSequentialGroup()
                .addGroup(rootPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootPNLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(thongTinMENU1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rootPNLayout.createSequentialGroup()
                        .addGroup(rootPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(rootPNLayout.createSequentialGroup()
                                .addComponent(backLB, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(445, 445, 445)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(26, 26, 26))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minisizeLB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(closeLB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rootPNLayout.setVerticalGroup(
            rootPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPNLayout.createSequentialGroup()
                .addGroup(rootPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backLB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(rootPNLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(rootPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(closeLB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minisizeLB, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rootPNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootPNLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 732, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rootPNLayout.createSequentialGroup()
                        .addComponent(thongTinMENU1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(203, 203, 203))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rootPN, javax.swing.GroupLayout.PREFERRED_SIZE, 603, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(rootPN, javax.swing.GroupLayout.PREFERRED_SIZE, 747, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeLBMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeLBMouseClicked

    private void minisizeLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minisizeLBMouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_minisizeLBMouseClicked
    int xx, yy;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed

        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseDragged

    private void dangXuatMENUITEMMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dangXuatMENUITEMMouseMoved
        setBorderMENU(dangXuatMENUITEM, 1);
    }//GEN-LAST:event_dangXuatMENUITEMMouseMoved

    private void dangXuatMENUITEMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dangXuatMENUITEMMouseClicked
        this.dispose();
//        LoginFrame jLogin = new LoginFrame();
//        jLogin.setVisible(true);
    }//GEN-LAST:event_dangXuatMENUITEMMouseClicked

    private void dangXuatMENUITEMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dangXuatMENUITEMMouseExited
        setBorderMENU(dangXuatMENUITEM, 0);
    }//GEN-LAST:event_dangXuatMENUITEMMouseExited

    private void doiMatKhauMENUITEMMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doiMatKhauMENUITEMMouseMoved
        setBorderMENU(doiMatKhauMENUITEM, 1);
		}//GEN-LAST:event_doiMatKhauMENUITEMMouseMoved

    private void doiMatKhauMENUITEMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doiMatKhauMENUITEMMouseClicked
        ChangePassword changePassword = new ChangePassword();
        changePassword.nguoiDung = maNguoiDung;
        System.out.println(maNguoiDung);
        changePassword.matKhau = matKhau;
        changePassword.setVisible(true);
    }//GEN-LAST:event_doiMatKhauMENUITEMMouseClicked

    private void doiMatKhauMENUITEMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doiMatKhauMENUITEMMouseExited
        setBorderMENU(doiMatKhauMENUITEM, 0);
    }//GEN-LAST:event_doiMatKhauMENUITEMMouseExited

    private void thongTinTaiKhoanMENUITEMMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongTinTaiKhoanMENUITEMMouseMoved
        setBorderMENU(thongTinTaiKhoanMENUITEM, 1);
    }//GEN-LAST:event_thongTinTaiKhoanMENUITEMMouseMoved

    private void thongTinTaiKhoanMENUITEMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongTinTaiKhoanMENUITEMMouseClicked
        // tạo 1 form đầy đủ thông tin

    }//GEN-LAST:event_thongTinTaiKhoanMENUITEMMouseClicked

    private void thongTinTaiKhoanMENUITEMMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongTinTaiKhoanMENUITEMMouseExited
        setBorderMENU(thongTinTaiKhoanMENUITEM, 0);
    }//GEN-LAST:event_thongTinTaiKhoanMENUITEMMouseExited

    private void thongTinMENUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongTinMENUMouseExited
        setBorderMENU(thongTinMENU, 0);
    }//GEN-LAST:event_thongTinMENUMouseExited

    private void thongTinMENUMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongTinMENUMouseMoved
        setBorderMENU(thongTinMENU, 1);
    }//GEN-LAST:event_thongTinMENUMouseMoved

    private void phanCongMENUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phanCongMENUMouseExited
        setBorderMENU(phanCongMENU, 0);
    }//GEN-LAST:event_phanCongMENUMouseExited

    private void phanCongMENUMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phanCongMENUMouseMoved
        setBorderMENU(phanCongMENU, 1);
    }//GEN-LAST:event_phanCongMENUMouseMoved

    private void thongKeMENUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongKeMENUMouseExited
        setBorderMENU(thongKeMENU, 0);
    }//GEN-LAST:event_thongKeMENUMouseExited

    private void thongKeMENUMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongKeMENUMouseMoved
        setBorderMENU(thongKeMENU, 1);
    }//GEN-LAST:event_thongKeMENUMouseMoved

    private void timKiemMENUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timKiemMENUMouseExited
        setBorderMENU(timKiemMENU, 0);
    }//GEN-LAST:event_timKiemMENUMouseExited

    private void timKiemMENUMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timKiemMENUMouseMoved
        setBorderMENU(timKiemMENU, 1);
    }//GEN-LAST:event_timKiemMENUMouseMoved

    private void baoCaoMENUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baoCaoMENUMouseExited
        setBorderMENU(baoCaoMENU, 0);
    }//GEN-LAST:event_baoCaoMENUMouseExited

    private void baoCaoMENUMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baoCaoMENUMouseMoved
        setBorderMENU(baoCaoMENU, 1);
    }//GEN-LAST:event_baoCaoMENUMouseMoved

    private void caiDatMENUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caiDatMENUMouseExited
        setBorderMENU(caiDatMENU, 0);
    }//GEN-LAST:event_caiDatMENUMouseExited

    private void caiDatMENUMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caiDatMENUMouseMoved
        setBorderMENU(caiDatMENU, 1);
    }//GEN-LAST:event_caiDatMENUMouseMoved

    private void quanLyMENUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanLyMENUMouseExited
        setBorderMENU(quanLyMENU, 0);
    }//GEN-LAST:event_quanLyMENUMouseExited

    private void quanLyMENUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanLyMENUMouseClicked
        MENUCard.show(CardMenu, MANAGERMENU);
    }//GEN-LAST:event_quanLyMENUMouseClicked

    private void quanLyMENUMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quanLyMENUMouseMoved
        setBorderMENU(quanLyMENU, 1);
    }//GEN-LAST:event_quanLyMENUMouseMoved

    private void taiKhoanMENUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taiKhoanMENUMouseExited
        setBorderMENU(taiKhoanMENU, 0);
    }//GEN-LAST:event_taiKhoanMENUMouseExited

    private void taiKhoanMENUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taiKhoanMENUMouseClicked
        MENUCard.show(CardMenu, ACCOUNTMENU);
    }//GEN-LAST:event_taiKhoanMENUMouseClicked

    private void taiKhoanMENUMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taiKhoanMENUMouseMoved
        setBorderMENU(taiKhoanMENU, 1);
    }//GEN-LAST:event_taiKhoanMENUMouseMoved

    private void backLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLBMouseClicked
        MENUCard.show(CardMenu, MENUMAIN);
    }//GEN-LAST:event_backLBMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        dangXuat();
    }//GEN-LAST:event_formWindowClosed

    private void caiDatMENUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caiDatMENUMouseClicked
        MENUCard.show(CardMenu, TEST);
    }//GEN-LAST:event_caiDatMENUMouseClicked

    private void thongKeMENUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongKeMENUMouseClicked
        SatisticalFrame st=new SatisticalFrame();
        st.setVisible(true);
    }//GEN-LAST:event_thongKeMENUMouseClicked

    private void timKiemMENUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timKiemMENUMouseClicked
        // TODO add your handling code here:
        MENUCard.show(CardMenu,Search);
    }//GEN-LAST:event_timKiemMENUMouseClicked

    private void quanLySinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLySinhVienActionPerformed
        InfoStudent infoStudent = new InfoStudent();
        infoStudent.setVisible(true);
    }//GEN-LAST:event_quanLySinhVienActionPerformed

    private void quanLyHocPhan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyHocPhan2ActionPerformed
        InfoSubject frame = new InfoSubject();
        frame.setVisible(true);
    }//GEN-LAST:event_quanLyHocPhan2ActionPerformed

    private void quanLyHocPhan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyHocPhan1ActionPerformed
        // TODO add your handling code here:
        InfoAssignmentForClass pchd=new InfoAssignmentForClass("");
        pchd.setVisible(true);
    }//GEN-LAST:event_quanLyHocPhan1ActionPerformed

    private void quanLyHocPhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyHocPhanActionPerformed
        AssignmentDetailsForAStudent pcct = new AssignmentDetailsForAStudent("");
        pcct.setVisible(true);
    }//GEN-LAST:event_quanLyHocPhanActionPerformed

    private void quanLyLoaiHinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyLoaiHinhActionPerformed
        InfoType infoType = new InfoType();
        infoType.setVisible(true);
    }//GEN-LAST:event_quanLyLoaiHinhActionPerformed

    private void quanLyGiangVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quanLyGiangVienActionPerformed
        InfoTeacher infoTeacher = new InfoTeacher();
        infoTeacher.setVisible(true);
    }//GEN-LAST:event_quanLyGiangVienActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        SearchTeacher teacher=new SearchTeacher();
        teacher.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SearchSubject subject=new SearchSubject();
        subject.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void timKiemSinhVienBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timKiemSinhVienBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timKiemSinhVienBtnActionPerformed

    private void timKiemSinhVienBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timKiemSinhVienBtnMouseClicked
        SearchStudent frame = new SearchStudent();
        frame.setVisible(true);
    }//GEN-LAST:event_timKiemSinhVienBtnMouseClicked

    private void thongTinMENU1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongTinMENU1MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_thongTinMENU1MouseMoved

    private void thongTinMENU1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongTinMENU1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_thongTinMENU1MouseExited

    private void thongTinMENU2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongTinMENU2MouseMoved
        setBorderMENU(thongTinMENU2, 1);
    }//GEN-LAST:event_thongTinMENU2MouseMoved

    private void thongTinMENU2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thongTinMENU2MouseExited
        setBorderMENU(thongTinMENU2, 0);
    }//GEN-LAST:event_thongTinMENU2MouseExited

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void phanCongMENUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phanCongMENUMouseClicked
        KeKhaiFrame frame = new KeKhaiFrame(maNguoiDung);
        frame.setVisible(true);
    }//GEN-LAST:event_phanCongMENUMouseClicked

    private void baoCaoMENUMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baoCaoMENUMouseClicked
        ReportFrame frame = new ReportFrame();
        frame.setVisible(true);
    }//GEN-LAST:event_baoCaoMENUMouseClicked
    private void dangXuat() {
//        this.dispose();
//        main.login.setVisible(true);
        LoginFrame login = new LoginFrame();
        login.setVisible(true); 
    }
    
    private void setBorderMENU(JLabel LB, int i) {
        if (i == 0) {
            LB.setBorder(null);
        } else {
            LB.setBorder(createLineBorder(color.Color.BORDER, THICKNESS));
        }
    }

    private void setOptionMenu() {
        listOptionMenu.add(ACCOUNT, taiKhoanMENU);
        listOptionMenu.add(MANAGER, quanLyMENU);
        listOptionMenu.add(SETTING, caiDatMENU);
        listOptionMenu.add(SEARCH, timKiemMENU);
        listOptionMenu.add(STATISTICAL, thongKeMENU);
        listOptionMenu.add(REPORT, baoCaoMENU);
        listOptionMenu.add(ASSIGNMENT, phanCongMENU);
        listOptionMenu.add(INFOMATION, thongTinMENU);
    }
    
    public static void main(String[] args) {
        Main3 frame = new Main3("admin", 1);
        frame.setVisible(true);
    }

    private ArrayList<JLabel> listOptionMenu = new ArrayList<>();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CardMenu;
    private javax.swing.JPanel Timkiem;
    private javax.swing.JLabel backLB;
    private javax.swing.JLabel baoCaoMENU;
    private javax.swing.JLabel caiDatMENU;
    private javax.swing.JLabel closeLB;
    private javax.swing.JLabel dangXuatMENUITEM;
    private javax.swing.JLabel doiMatKhauMENUITEM;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel minisizeLB;
    private javax.swing.JLabel phanCongMENU;
    private javax.swing.JButton quanLyGiangVien2;
    private javax.swing.JButton quanLyHocPhan6;
    private javax.swing.JButton quanLyHocPhan7;
    private javax.swing.JButton quanLyHocPhan8;
    private javax.swing.JButton quanLyLoaiHinh2;
    private javax.swing.JLabel quanLyMENU;
    private javax.swing.JButton quanLySinhVien2;
    private javax.swing.JLabel quyenTF;
    private javax.swing.JPanel rootPN;
    private javax.swing.JLabel taiKhoanMENU;
    private javax.swing.JLabel tenNguoiDungTF;
    private javax.swing.JPanel test;
    private javax.swing.JPanel theChucNangChinh;
    private javax.swing.JPanel theQuanLy2;
    private javax.swing.JPanel theTaiKhoan;
    private javax.swing.JLabel thongKeMENU;
    private javax.swing.JLabel thongTinMENU;
    private javax.swing.JLabel thongTinMENU1;
    private javax.swing.JLabel thongTinMENU2;
    private javax.swing.JLabel thongTinTaiKhoanMENUITEM;
    private javax.swing.JLabel timKiemMENU;
    private javax.swing.JButton timKiemSinhVienBtn;
    // End of variables declaration//GEN-END:variables
}
